services:
  db:
    build: ./db
    restart: always
    container_name: ${PROJECT_NAME}_db
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=5432
    networks:
      - app_network
    # networks:
    #   app_network:
    #     ipv4_address: 172.${NETWORK_PORT}.0.3

  web:
    build: ./web
    user: "33:33" # linux for www-data:www-data and docker uses linux vm"
    restart: always
    healthcheck:
      test: ["CMD", "python3", "manage.py", "check"]
      interval: 30s
      timeout: 5s
      retries: 3
    container_name: ${PROJECT_NAME}_web
    ports:
      - "${CONTAINER_PORT}:${CONTAINER_PORT}"
    depends_on:
      - db
    volumes:
      - ./web:/app
      # Comment out when DEBUG = True:
      - /srv/docker/social_media/staticfiles:/app/staticfiles
      - /srv/docker/social_media/media:/app/media
      - /srv/docker/social_media/logs:/app/logs
    networks:
      - app_network
    # networks:
    #   app_network:
    #     ipv4_address: 172.${NETWORK_PORT}.0.3

volumes:
  postgres_data:

networks:
  app_network:
    name: ${NETWORK_NAME}
    driver: bridge
    # ipam:
    #   config:
    #     - subnet: 172.${NETWORK_PORT}.0.0/16